# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 07:58
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100, verbose_name='Keyword')),
            ],
            options={
                'ordering': ['pk'],
                'get_latest_by': 'pk',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('type', models.CharField(choices=[('TWITTER', 'Twitter')], default='TWITTER', max_length=50, verbose_name='Type')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='INACTIVE', max_length=50, verbose_name='Status')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
            ],
            options={
                'ordering': ['pk'],
                'get_latest_by': 'pk',
            },
        ),
        migrations.CreateModel(
            name='Twitter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.BigIntegerField(verbose_name='Tweet ID')),
                ('tweet_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tweet Created')),
                ('tweet_text', models.TextField(blank=True, verbose_name='Tweet Text')),
                ('user_id', models.BigIntegerField(verbose_name='User ID')),
                ('user_name', models.CharField(max_length=100, verbose_name='User Name')),
                ('user_screen_name', models.CharField(max_length=100, verbose_name='User Screen Name')),
                ('user_utc_offset', models.IntegerField(verbose_name='User UTC Offset')),
                ('user_coordinate', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='User Coordinate')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweets', to='aggregator.Keyword', verbose_name='Keyword')),
            ],
            options={
                'ordering': ['pk'],
                'get_latest_by': 'pk',
            },
        ),
        migrations.AddField(
            model_name='keyword',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='aggregator.Source', verbose_name='Source'),
        ),
    ]
