# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='method',
            field=models.CharField(choices=[('TWEEPY', 'TWEEPY'), ('GOT', 'GOT')], default='TWEEPY', max_length=50, verbose_name='Method'),
        ),
        migrations.AddField(
            model_name='source',
            name='since',
            field=models.DateField(blank=True, null=True, verbose_name='Since'),
        ),
        migrations.AddField(
            model_name='source',
            name='until',
            field=models.DateField(blank=True, null=True, verbose_name='Until'),
        ),
        migrations.AddField(
            model_name='source',
            name='username',
            field=models.CharField(blank=True, max_length=50, verbose_name='User Name'),
        ),
    ]
