# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0002_retweet_source_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='source_property',
            name='user_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='User Name'),
        ),
    ]
