# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0002_auto_20160615_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitter',
            name='user_utc_offset',
            field=models.IntegerField(blank=True, null=True, verbose_name='User UTC Offset'),
        ),
    ]
