# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0003_auto_20160616_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitter',
            name='user_URL',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='User URL'),
        ),
        migrations.AlterField(
            model_name='twitter',
            name='user_id',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='twitter',
            name='user_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='User Name'),
        ),
    ]
