# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0004_auto_20160622_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitter',
            name='user_location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='User Location'),
        ),
        migrations.AlterField(
            model_name='twitter',
            name='keyword',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tweets', to='aggregator.Keyword', verbose_name='Keyword'),
        ),
        migrations.AlterField(
            model_name='twitter',
            name='user_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='User ID'),
        ),
    ]
