# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-15 11:00
from __future__ import unicode_literals

import aggregator.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0005_auto_20170615_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AddField(
            model_name='twitter',
            name='categories',
            field=aggregator.models.CustomMultiSelectField(blank=True, choices=[('placeholder', 'placeholder')], max_length=1000),
        ),
        migrations.AddField(
            model_name='twitter',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
