# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-15 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0006_auto_20170615_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitter',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
