# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 17:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0008_auto_20160627_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twitter',
            old_name='tags',
            new_name='tags_tweet',
        ),
    ]
