# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 18:40
from __future__ import unicode_literals

from django.db import migrations
import taggit_autocomplete_modified.managers


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0009_auto_20160627_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitter',
            name='tags_tweet',
            field=taggit_autocomplete_modified.managers.TaggableManagerAutocomplete(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
