# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 19:14
from __future__ import unicode_literals

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0011_auto_20160627_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitter',
            name='favorites',
            field=models.IntegerField(blank=True, null=True, verbose_name='Favorites'),
        ),
        migrations.AddField(
            model_name='twitter',
            name='retweets',
            field=models.IntegerField(blank=True, null=True, verbose_name='Retweets'),
        ),
        migrations.AlterField(
            model_name='twitter',
            name='tags_tweet',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
