# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 11:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import taggit_autosuggest.managers


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0012_auto_20160628_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitter',
            name='favorites',
            field=models.IntegerField(blank=True, default=0, verbose_name='Favorites'),
        ),
        migrations.AlterField(
            model_name='twitter',
            name='keyword',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tweets', to='aggregator.Keyword', verbose_name='Keyword'),
        ),
        migrations.AlterField(
            model_name='twitter',
            name='retweets',
            field=models.IntegerField(blank=True, default=0, verbose_name='Retweets'),
        ),
        migrations.AlterField(
            model_name='twitter',
            name='tags_tweet',
            field=taggit_autosuggest.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
